### ISSUE TITLE
Im getting this error how do i fix? 

### ISSUE THREAD

**Issue by Rohanzz0908** [aryan0078/dabby#4]
how do i fix this mongo error?
<img width="386" alt="Screenshot 2021-09-25 165949" src="https://user-images.githubusercontent.com/91373709/134769933-d106a1c9-0db0-4450-99f0-58dd122e1cb3.png">

**Comment by Rohanzz0908** [comment]
@aryan0078

**Comment by aryan0078** [comment]
Please install mongodb and setup it then use it

**Comment by Rohanzz0908** [comment]
> Please install mongodb and setup it then use it

Iv did it but im getting new errors can u pls help?
<img width="394" alt="Screenshot 2021-09-26 103529" src="https://user-images.githubusercontent.com/91373709/134794440-1ea10f68-69b5-4c10-8f7d-681d2725b849.png">
@aryan0078

**Comment by aryan0078** [comment]
remove any other const url from that file

**Comment by Rohanzz0908** [comment]
> remove any other const url from that file

nah not working iv tried to fix but new errors.... And can i get your discord tag
<img width="396" alt="OP" src="https://user-images.githubusercontent.com/91373709/134795198-1e36628f-507b-4b75-a6ac-dfa285b2f652.png">
@aryan0078

**Comment by aryan0078** [comment]
Create a PR i will patch it and make sure u installed mongodb before running

**Comment by Rohanzz0908** [comment]
bruh i fixed that mongo part this new error... @aryan0078 
<img width="403" alt="ff" src="https://user-images.githubusercontent.com/91373709/134799469-6a68e59b-9ac2-4c0d-85bb-0d764a9b0043.png">

**Comment by aryan0078** [comment]
Please provide proper token
